from fastapi import APIRouter, HTTPException, status, Depends, Request
from fastapi.responses import RedirectResponse
from typing import List, Optional
import stripe
import os

stripe.api_key = os.getenv("STRIPE_SECRET_KEY", "-")
from models.domain import Order, Courier, DeliveryStatus, UserCreate, UserResponse
from services.business_logic import DeliveryService
from sqlalchemy.orm import Session
from database import get_db, CourierDB, OrderDB, UserDB
from repositories.order_repository import OrderRepository

router = APIRouter()

@router.get("/health", tags=["system"])
def health_check():
    return {"status": "ok"}

# --- Order Service ---
@router.post("/orders/", response_model=Order, status_code=status.HTTP_201_CREATED)
def create_order(order: Order, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    if repo.get_by_id(order.id):
        raise HTTPException(status_code=400, detail="Order with this ID already exists")
    
    order_dict = order.dict(exclude_none=True)
    
    if order.client_id:
        user = db.query(UserDB).filter(UserDB.id == order.client_id).first()
        if not user:
            raise HTTPException(status_code=404, detail="Клієнта з таким ID не знайдено")
        order_dict['client_name'] = user.name
        order_dict['client_phone'] = user.phone or order_dict.get('client_phone')
        order_dict['client_address'] = user.address or order_dict.get('client_address')
    elif order.client_name and order.client_phone and order.client_address:
        # Шукаємо чи є такий клієнт у базі (поєднання імені та телефону)
        existing_user = db.query(UserDB).filter(
            UserDB.phone == order.client_phone,
            UserDB.name == order.client_name
        ).first()
        
        if existing_user:
            # Прив'язуємо до існуючого клієнта
            order_dict['client_id'] = existing_user.id
        else:
            # Створюємо нового клієнта автоматично для уникнення дублікатів у майбутньому
            import uuid
            temp_email = f"client_{order.client_phone}_{uuid.uuid4().hex[:6]}@guest.local"
            
            new_user = UserDB(
                name=order.client_name,
                phone=order.client_phone,
                address=order.client_address,
                email=temp_email,
                password="AutoGeneratedPassword1"
            )
            db.add(new_user)
            db.commit()
            db.refresh(new_user)
            order_dict['client_id'] = new_user.id
            
    else:
        raise HTTPException(status_code=400, detail="Must provide either client_id or full client details (name, phone, address)")

    new_order = repo.create(order_dict)
    
    return new_order

@router.get("/orders/", response_model=List[Order])
def get_all_orders(
    skip: int = 0, 
    limit: int = 10, 
    status_filter: Optional[str] = None,
    sort_by: Optional[str] = None,
    db: Session = Depends(get_db)
):
    repo = OrderRepository(db)
    return repo.get_all(skip=skip, limit=limit, status_filter=status_filter, sort_by=sort_by)

@router.get("/orders/{order_id}", response_model=Order)
def get_order(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    return order

@router.patch("/orders/{order_id}/status", response_model=Order)
def update_status(order_id: int, new_status: str, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    # Якщо статус змінюється на завершений, звільняємо кур'єра
    if new_status in [DeliveryStatus.DELIVERED.value, DeliveryStatus.CANCELLED.value]:
        courier = db.query(CourierDB).filter(CourierDB.current_order_id == order_id).first()
        if courier:
            courier.is_available = True
            courier.current_order_id = None
            courier.destination = None
            db.commit()

    order = repo.update(order_id, {"status": new_status})
    return order

@router.post("/orders/{order_id}/assign", response_model=Order)
def assign_courier(order_id: int, db: Session = Depends(get_db)):
    try:
        return DeliveryService.auto_assign_courier(order_id, db)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=409, detail=str(e))

@router.post("/orders/{order_id}/notify-arrival")
def notify_arrival(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    if order.status not in [DeliveryStatus.IN_TRANSIT.value, DeliveryStatus.ASSIGNED.value]:
        raise HTTPException(status_code=400, detail="Cannot notify arrival. Courier is not on the way.")
        
    order = repo.update(order_id, {"status": DeliveryStatus.WAITING.value})
    
    message = f"Шановний {order.client_name}, ваш кур'єр очікує під дверима за адресою {order.client_address}!"
    return {"message": message, "order_status": order.status}

@router.put("/orders/{order_id}", response_model=Order)
def replace_order(order_id: int, updated_order: Order, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    if not repo.get_by_id(order_id):
        raise HTTPException(status_code=404, detail="Order not found")
    
    update_data = {
        "client_name": updated_order.client_name,
        "client_phone": updated_order.client_phone,
        "client_address": updated_order.client_address,
        "status": updated_order.status,
        "courier_id": updated_order.courier_id,
        "route": updated_order.route
    }
    return repo.update(order_id, update_data)

@router.post("/orders/{order_id}/create-checkout-session")
def create_checkout_session(order_id: int, request: Request, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
        
    if order.status != DeliveryStatus.AWAITING_PAYMENT.value:
        raise HTTPException(status_code=400, detail="Замовлення вже оплачено або скасовано.")
        
    base_url = str(request.base_url).strip("/")
        
    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'uah',
                    'product_data': {
                        'name': f'Замовлення #{order.id}',
                        'description': f'Доставка: {order.client_address}',
                    },
                    'unit_amount': int((order.price or 100.0) * 100), # Stripe amount in smallest currency unit (kopiyok)
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url=f"{base_url}/orders/{order.id}/payment/success?session_id={{CHECKOUT_SESSION_ID}}",
            cancel_url=f"{base_url}/",
        )
        return {"checkout_url": session.url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/orders/{order_id}/payment/success")
def payment_success(order_id: int, session_id: str, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
        
    # Mark as Paid (CREATED means it's ready for courier assignment)
    repo.update(order_id, {"status": DeliveryStatus.CREATED.value})
    
    return RedirectResponse(url="/")

@router.delete("/orders/{order_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_order(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
        
    if order.status in [DeliveryStatus.ASSIGNED.value, DeliveryStatus.IN_TRANSIT.value, DeliveryStatus.WAITING.value]:
        raise HTTPException(status_code=400, detail="Неможливо видалити замовлення, на яке зараз призначено кур'єра. Спочатку дочекайтеся доставки або скасуйте його.")
        
    if not repo.delete(order_id):
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
    return None

# --- Courier Service ---
@router.get("/couriers/", response_model=List[Courier])
def get_all_couriers(db: Session = Depends(get_db)):
    # Беремо всіх кур'єрів з бази
    couriers = db.query(CourierDB).all()
    return couriers

@router.delete("/couriers/{courier_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_courier(courier_id: int, db: Session = Depends(get_db)):
    courier = db.query(CourierDB).filter(CourierDB.id == courier_id).first()
    if not courier:
        raise HTTPException(status_code=404, detail="Courier not found")
    
    db.delete(courier)
    db.commit()

# --- Tracking Service ---
@router.get("/tracking/{order_id}")
def track_order(order_id: int, db: Session = Depends(get_db)):
    # 1. Шукаємо замовлення в базі даних SQLite
    order = db.query(OrderDB).filter(OrderDB.id == order_id).first()
    
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    
    location = "Невідомо"
    
    # 2. Якщо замовленню призначено кур'єра, шукаємо його локацію в базі
    if order.courier_id:
        courier = db.query(CourierDB).filter(CourierDB.id == order.courier_id).first()
        if courier and courier.current_location:
            location = courier.current_location
            
    return {"order_id": order.id, "status": order.status, "current_location": location}

# --- Reporting Service ---
@router.get("/reports/deliveries")
def get_delivery_report(db: Session = Depends(get_db)):
    return DeliveryService.generate_report(db)

@router.get("/reports/daily")
def get_daily_statistics(date: str, db: Session = Depends(get_db)):
    # date in format YYYY-MM-DD
    try:
        return DeliveryService.get_daily_statistics(db, target_date=date)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@router.get("/reports/weekly")
def get_weekly_statistics(db: Session = Depends(get_db)):
    return DeliveryService.get_weekly_statistics(db)

# --- User Service ---
@router.get("/users/", response_model=List[UserResponse])
def get_all_users(db: Session = Depends(get_db)):
    users = db.query(UserDB).all()
    return users

@router.post("/users/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def create_user(user: UserCreate, db: Session = Depends(get_db)):
    existing_user = db.query(UserDB).filter(UserDB.email == user.email).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="User with this email already exists")
    
    new_user = UserDB(
        name=user.name,
        email=user.email,
        password=user.password, # В реальному проєкті пароль обов'язково треба хешувати
        phone=user.phone,
        address=user.address
    )
    
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    
    return new_user

@router.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user(user_id: int, db: Session = Depends(get_db)):
    user = db.query(UserDB).filter(UserDB.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    db.delete(user)
    db.commit()
