import os
import uuid
import httpx
import stripe
from fastapi import FastAPI, HTTPException, status, Depends, Request
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException
from datetime import datetime, timezone
from typing import List, Optional
from sqlalchemy.orm import Session

from database import get_db, OrderDB, UserDB, create_tables
from models import Order, DeliveryStatus, UserCreate, UserResponse
from repository import OrderRepository
from cache import cacheable, cache_evict, cache_flush_all

stripe.api_key = os.getenv("STRIPE_SECRET_KEY", "-")
COURIER_SERVICE_URL = os.getenv("COURIER_SERVICE_URL", "http://localhost:8002")

app = FastAPI(title="Order Service", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def create_error_format(status_code: int, message: str, path: str):
    return JSONResponse(
        status_code=status_code,
        content={
            "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "status": status_code,
            "message": message,
            "path": path
        }
    )


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    return create_error_format(exc.status_code, exc.detail, request.url.path)


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return create_error_format(422, "Помилка валідації даних", request.url.path)


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    return create_error_format(500, "Внутрішня помилка сервера", request.url.path)


@app.on_event("startup")
def on_startup():
    create_tables()


@app.get("/health", tags=["system"])
def health_check():
    return {"service": "order_service", "status": "ok"}


# --- Orders ---
@app.post("/orders/", response_model=Order, status_code=status.HTTP_201_CREATED)
def create_order(order: Order, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    if repo.get_by_id(order.id):
        raise HTTPException(status_code=400, detail="Order with this ID already exists")

    order_dict = order.dict(exclude_none=True)

    if order.client_id:
        user = db.query(UserDB).filter(UserDB.id == order.client_id).first()
        if not user:
            raise HTTPException(status_code=404, detail="Клієнта з таким ID не знайдено")
        order_dict['client_name'] = user.name
        order_dict['client_phone'] = user.phone or order_dict.get('client_phone')
        order_dict['client_address'] = user.address or order_dict.get('client_address')
    elif order.client_name and order.client_phone and order.client_address:
        existing_user = db.query(UserDB).filter(
            UserDB.phone == order.client_phone,
            UserDB.name == order.client_name
        ).first()
        if existing_user:
            order_dict['client_id'] = existing_user.id
        else:
            temp_email = f"client_{order.client_phone}_{uuid.uuid4().hex[:6]}@guest.local"
            new_user = UserDB(
                name=order.client_name,
                phone=order.client_phone,
                address=order.client_address,
                email=temp_email,
                password="AutoGeneratedPassword1"
            )
            db.add(new_user)
            db.commit()
            db.refresh(new_user)
            order_dict['client_id'] = new_user.id
    else:
        raise HTTPException(status_code=400, detail="Must provide either client_id or full client details (name, phone, address)")

    result = repo.create(order_dict)
    cache_evict("orders")
    return result


@app.get("/orders/", response_model=List[Order])
@cacheable("orders:list", ttl=30)
def get_all_orders(
    skip: int = 0,
    limit: int = 10,
    status_filter: Optional[str] = None,
    sort_by: Optional[str] = None,
    db: Session = Depends(get_db)
):
    repo = OrderRepository(db)
    return repo.get_all(skip=skip, limit=limit, status_filter=status_filter, sort_by=sort_by)


@app.get("/orders/{order_id}", response_model=Order)
@cacheable("orders:detail", ttl=30)
def get_order(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    return order


@app.patch("/orders/{order_id}/status", response_model=Order)
def update_status(order_id: int, new_status: str, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    if new_status in [DeliveryStatus.DELIVERED.value, DeliveryStatus.CANCELLED.value]:
        if order.courier_id:
            try:
                with httpx.Client(timeout=5.0) as client:
                    client.post(f"{COURIER_SERVICE_URL}/couriers/{order.courier_id}/free")
            except Exception:
                pass

    result = repo.update(order_id, {"status": new_status})
    cache_evict("orders")
    return result


@app.post("/orders/{order_id}/assign", response_model=Order)
def assign_courier(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    if order.status == DeliveryStatus.AWAITING_PAYMENT.value:
        raise HTTPException(status_code=400, detail="Замовлення очікує оплати. Спочатку проведіть оплату.")
    if order.status != DeliveryStatus.CREATED.value:
        raise HTTPException(status_code=409, detail="Order is already assigned or in progress")

    try:
        with httpx.Client(timeout=5.0) as client:
            response = client.post(
                f"{COURIER_SERVICE_URL}/couriers/assign-order",
                json={"order_id": order_id, "order_address": order.client_address}
            )
            if response.status_code == 404:
                raise HTTPException(status_code=404, detail="Немає вільних кур'єрів")
            if response.status_code >= 400:
                detail = response.json().get("detail", "Courier service error")
                raise HTTPException(status_code=response.status_code, detail=detail)

            data = response.json()
    except HTTPException:
        raise
    except httpx.RequestError:
        raise HTTPException(status_code=503, detail="Courier service unavailable")

    updated_order = repo.update(order_id, {
        "courier_id": data["courier_id"],
        "status": DeliveryStatus.ASSIGNED.value,
        "route": data["route"]
    })
    cache_evict("orders")
    return updated_order


@app.post("/orders/{order_id}/notify-arrival")
def notify_arrival(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    if order.status not in [DeliveryStatus.IN_TRANSIT.value, DeliveryStatus.ASSIGNED.value]:
        raise HTTPException(status_code=400, detail="Cannot notify arrival. Courier is not on the way.")
    order = repo.update(order_id, {"status": DeliveryStatus.WAITING.value})
    cache_evict("orders")
    message = f"Шановний {order.client_name}, ваш кур'єр очікує під дверима за адресою {order.client_address}!"
    return {"message": message, "order_status": order.status}


@app.put("/orders/{order_id}", response_model=Order)
def replace_order(order_id: int, updated_order: Order, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    if not repo.get_by_id(order_id):
        raise HTTPException(status_code=404, detail="Order not found")
    update_data = {
        "client_name": updated_order.client_name,
        "client_phone": updated_order.client_phone,
        "client_address": updated_order.client_address,
        "status": updated_order.status,
        "courier_id": updated_order.courier_id,
        "route": updated_order.route
    }
    result = repo.update(order_id, update_data)
    cache_evict("orders")
    return result


@app.post("/orders/{order_id}/create-checkout-session")
def create_checkout_session(order_id: int, request: Request, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
    if order.status != DeliveryStatus.AWAITING_PAYMENT.value:
        raise HTTPException(status_code=400, detail="Замовлення вже оплачено або скасовано.")
    base_url = str(request.base_url).strip("/")
    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'uah',
                    'product_data': {
                        'name': f'Замовлення #{order.id}',
                        'description': f'Доставка: {order.client_address}',
                    },
                    'unit_amount': int((order.price or 100.0) * 100),
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url=f"{base_url}/orders/{order.id}/payment/success?session_id={{CHECKOUT_SESSION_ID}}",
            cancel_url="http://localhost:8000/",
        )
        return {"checkout_url": session.url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/orders/{order_id}/payment/success")
def payment_success(order_id: int, session_id: str, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    repo.update(order_id, {"status": DeliveryStatus.CREATED.value})
    cache_evict("orders")
    return RedirectResponse(url="http://localhost:8000/")


@app.delete("/orders/{order_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_order(order_id: int, db: Session = Depends(get_db)):
    repo = OrderRepository(db)
    order = repo.get_by_id(order_id)
    if not order:
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
    if order.status in [DeliveryStatus.ASSIGNED.value, DeliveryStatus.IN_TRANSIT.value, DeliveryStatus.WAITING.value]:
        raise HTTPException(status_code=400, detail="Неможливо видалити замовлення, на яке зараз призначено кур'єра.")
    if not repo.delete(order_id):
        raise HTTPException(status_code=404, detail="Замовлення не знайдено")
    cache_evict("orders")
    return None


# --- Users ---
@app.get("/users/", response_model=List[UserResponse])
@cacheable("users:list", ttl=60)
def get_all_users(db: Session = Depends(get_db)):
    return db.query(UserDB).all()


@app.post("/users/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def create_user(user: UserCreate, db: Session = Depends(get_db)):
    existing_user = db.query(UserDB).filter(UserDB.email == user.email).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="User with this email already exists")
    new_user = UserDB(
        name=user.name, email=user.email, password=user.password,
        phone=user.phone, address=user.address
    )
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    cache_evict("users")
    return new_user


@app.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user(user_id: int, db: Session = Depends(get_db)):
    user = db.query(UserDB).filter(UserDB.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    db.delete(user)
    db.commit()
    cache_evict("users")


@app.post("/cache/flush", tags=["system"])
def flush_cache():
    count = cache_flush_all()
    return {"flushed_keys": count}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
