apiVersion: v1
kind: PersistentVolume
metadata:
  name: delivery-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/delivery-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-db-pvc
  namespace: delivery-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
